### PR TITLE
Prebuilt

### PR DESCRIPTION
**Pull request by thetheodor**

### CODE REVIEW

**Review by Quarub — COMMENTED** [review]
Could you also include the Dockerfile for the container so it doesn't get lost?

**Comment by thetheodor** [comment]
> Could you also include the Dockerfile for the container so it doesn't get lost?

I placed it here as it's not really specific to the instrumenter, e.g., I'm also using it here: https://github.com/DeadCodeProductions/callchain-checker

https://github.com/thetheodor/manylinux-with-llvm

**Comment by thetheodor** [comment]
> Could you also include the Dockerfile for the container so it doesn't get lost?

Added a reference to readme

**Comment by thetheodor** [comment]
@Quarub shall I merge this?

**Review by Quarub — APPROVED** [review]

**Pull request merged**
